apiVersion: # v1
kind: # Pod
metadata: # Pod의 메타데이터 
  name:
  labels:
    # 원하는 라벨 명: 라벨 값
    # greoup: web
    # app: app-1
    # version: v1
    # env: prod
spec:
  containers: # --------------------------------------------------------------------------containers
  - name: # webapp-1
    image: # nginx:latest
    ports:
      - containerPort: # 80
        protocol: # TCP
    resources:
    env: # 컨테이너 환경 변수 설정
      - name: # 변수 이름
        value: # 정의
      - name:
        valueFrom:
          fieldRef:
            fieldPath: # ex) metadata.namespace, status.hostIP 등
    command: ['sh', '-c', 'echo The app is running! && sleep 3600'] # 컨테이너 자동 종료를 방지하는 커맨드
  - name: # 이런 식으로 spec > containers 안에 하나의 pod에서 sidecar 구성이 가능하다
    # image:
    # command: ...

  nodeSelector: # ----------------------------------------------------------------------nodeSelector
    # project: node
    # 노드에 부착된 라벨 명: 라벨 값
    # pod 생성 시 해당 라벨이 부착된 node에 pod가 배치된다.
