---
- name: "Script Send and Run"
  hosts: all
  become: yes
  become_method: sudo
  vars:
    local_path: /root/ansible/playbook
    remote_path: /root
  tasks:
    - name: "Script Send"
      copy:
        src: "{{ local_path }}/initscript.sh"
        dest: "{{ remote_path }}/initscript.sh"
        owner: root
        group: root
        mode: 755
    - name: "Script Run"
      ignore_errors: yes
      shell:
        cmd: |
          {{ remote_path }}/initscript.sh
